version: '3'
services:
  bot:
    build: .
    environment:
      - COMMIT_HASH
      - PING_PONG_TOKEN
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN
      - TWITTER_ACCESS_TOKEN_SECRET
