name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}

      - name: Set enviroments of SSH
        env:
          PING_PONG_TOKEN: ${{ secrets.PING_PONG_TOKEN }}
        run: |
          for e in $(env); do
            k=$(echo $e | cut -d= -f1)
            v=$(echo $e | sed 's/^.*=//')
            if [ "x$k" = "x${k#GITHUB_}" ]; then
              echo "export $k='$v'" >>~/.ssh/enviroment
            fi
          done
        # run: "echo -e \"\
        #   PING_PONG_TOKEN=${{ secrets.PING_PONG_TOKEN }}\\n\
        #   \" > ~/.ssh/enviroment"

      - name: Check enviroment
        run: cat ~/.ssh/enviroment

      # - name: Update bot
      #   run: ssh deployment "~/bots/update_ping_pong.sh"
