name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}

      - name: Set enviroments of SSH
        run: |-
          echo -e "
          PING_PONG_TOKEN=${{ secrets.PING_PONG_TOKEN }}
          " > ~/.ssh/enviroment

      - name: Update bot
        run: ssh deployment "/home/discord/bots/update_ping_pong.sh"
