name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.CONFIG }}

      - name: Update bot
        run:
          ssh deployment "
          COMMIT_HASH=${GITHUB_SHA}
          PING_PONG_TOKEN=${{ secrets.PING_PONG_TOKEN }}
          TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          ~/bots/update_ping_pong.sh"
